export const teaseSequence = {
  id: "22222",
  name: "Tease", // z.B. 'Tease', 'Konsequenz'
  startMessage: "Bereit für ein wenig Spaß?", // Message, die zu beginn angezeigt wird
  endMessage: "Das war's für den Moment.", // Message, die am Ende angezeigt wird
  steps: [
    {
      t: 0,
      dur: 10,
      freq: 220,
      volume: 1,
      pan: -0.8,
      mood: "neutral",
      text: "Ganz ruhig. Wir beginnen klein.",
    },
    {
      t: 10,
      dur: 10,
      freq: 260,
      volume: 1,
      pan: 0.8,
      mood: "soft",
      text: "Oh? Da reagierst du sofort.",
    },
    {
      t: 20,
      dur: 10,
      freq: 320,
      volume: 2,
      pan: 0,
      mood: "strict",
      text: "Jetzt beide gleichzeitig.",
    },
    {
      t: 30,
      dur: 8,
      freq: 420,
      volume: 3,
      pan: -1,
      mood: "stare",
      text: "Da bist du plötzlich sehr aufmerksam.",
    },
    {
      t: 38,
      dur: 7,
      freq: 280,
      volume: 1,
      pan: 0.2,
      mood: "laugh",
      text: "Nicht gleich überfordert sein.",
    },
    {
      t: 45,
      dur: 15,
      freq: 360,
      volume: 2,
      pan: 0,
      mood: "pressure",
      text: "Atmen. Stillhalten.",
    },
    {
      t: 60,
      dur: 10,
      freq: 480,
      volume: 3,
      pan: 1,
      mood: "soft",
      text: "Sehr empfindlich. Wie praktisch.",
    },
    {
      t: 70,
      dur: 8,
      freq: 560,
      volume: 4,
      pan: -0.9,
      mood: "strict",
      text: "Und wieder zurück. Genau so.",
    },
    {
      t: 78,
      dur: 12,
      freq: 320,
      volume: 1,
      pan: 0,
      mood: "neutral",
      text: "Beruhig dich wieder.",
    },
    {
      t: 90,
      dur: 10,
      freq: 520,
      volume: 3,
      pan: -0.5,
      mood: "stare",
      text: "Nicht ausweichen.",
    },
    {
      t: 100,
      dur: 10,
      freq: 600,
      volume: 4,
      pan: 0.7,
      mood: "laugh",
      text: "Deine Reaktion verrät dich.",
    },
    {
      t: 110,
      dur: 10,
      freq: 420,
      volume: 2,
      pan: 0,
      mood: "pressure",
      text: "Jetzt wieder sammeln.",
    },
  ],
};

export const consequenceSequence = {
  id: "111111",
  name: "Konsequenz", // z.B. 'Tease', 'Konsequenz'
  startMessage: "Du wolltest nicht hören. Also brauchen wir Konsequenzen.", // Message, die zu beginn angezeigt wird
  endMessage: "Ich hoffe, das war dir eine Lehre.", // Message, die am Ende angezeigt wird
  steps: [
    {
      t: 0,
      dur: 6,
      freq: 360,
      volume: 2,
      pan: 0,
      mood: "strict",
      text: "Still. Jetzt wird nicht diskutiert.",
    },
    {
      t: 6,
      dur: 5,
      freq: 420,
      volume: 3,
      pan: -1,
      mood: "stare",
      text: "Das hast du nun davon.",
    },
    {
      t: 11,
      dur: 4,
      freq: 520,
      volume: 4,
      pan: 1,
      mood: "strict",
      text: "Ungehorsam hat Folgen.",
    },
    {
      t: 15,
      dur: 5,
      freq: 280,
      volume: 1,
      pan: 0,
      mood: "pressure",
      text: "Kurze Pause. Aber nicht zur Erholung.",
    },
    {
      t: 23,
      dur: 4,
      freq: 560,
      volume: 5,
      pan: -1,
      mood: "stare",
      text: "Überraschung.",
    },
    {
      t: 27,
      dur: 6,
      freq: 480,
      volume: 4,
      pan: 1,
      mood: "strict",
      text: "Du bleibst ruhig. Genau jetzt.",
    },
    {
      t: 33,
      dur: 7,
      freq: 320,
      volume: 2,
      pan: 0,
      mood: "neutral",
      text: "Ich führe. Du folgst.",
    },
    {
      t: 40,
      dur: 5,
      freq: 600,
      volume: 5,
      pan: -0.8,
      mood: "stare",
      text: "Zu spät für Reue.",
    },
    {
      t: 45,
      dur: 5,
      freq: 520,
      volume: 4,
      pan: 0.8,
      mood: "laugh",
      text: "Du wolltest testen, wie weit du kommst.",
    },
    {
      t: 50,
      dur: 6,
      freq: 360,
      volume: 2,
      pan: 0,
      mood: "strict",
      text: "Antwort: Nicht weit.",
    },
    {
      t: 60,
      dur: 4,
      freq: 600,
      volume: 5,
      pan: -1,
      mood: "stare",
      text: "Da ist die Konsequenz.",
    },
    {
      t: 64,
      dur: 4,
      freq: 560,
      volume: 5,
      pan: 1,
      mood: "strict",
      text: "Und gleich noch einmal.",
    },
    {
      t: 68,
      dur: 8,
      freq: 420,
      volume: 3,
      pan: 0,
      mood: "pressure",
      text: "Halte still. Sauber. Ohne Ausreden.",
    },
    {
      t: 76,
      dur: 5,
      freq: 480,
      volume: 4,
      pan: -1,
      mood: "stare",
      text: "Du lernst jetzt Aufmerksamkeit.",
    },
    {
      t: 81,
      dur: 5,
      freq: 520,
      volume: 4,
      pan: 1,
      mood: "strict",
      text: "Und zwar nicht irgendwann. Jetzt.",
    },
    {
      t: 86,
      dur: 6,
      freq: 280,
      volume: 1,
      pan: 0,
      mood: "laugh",
      text: "Oh, glaubst du, es wird leichter?",
    },
    {
      t: 96,
      dur: 4,
      freq: 600,
      volume: 5,
      pan: 0,
      mood: "stare",
      text: "Falsch.",
    },
    {
      t: 100,
      dur: 6,
      freq: 560,
      volume: 5,
      pan: -1,
      mood: "strict",
      text: "Konzentrier dich.",
    },
    {
      t: 106,
      dur: 6,
      freq: 520,
      volume: 4,
      pan: 1,
      mood: "pressure",
      text: "Jede kleine Reaktion wird bemerkt.",
    },
    {
      t: 112,
      dur: 8,
      freq: 420,
      volume: 3,
      pan: 0,
      mood: "strict",
      text: "Du bist nicht hier, um bequem zu sein.",
    },
    {
      t: 120,
      dur: 5,
      freq: 600,
      volume: 5,
      pan: -0.9,
      mood: "stare",
      text: "Du bist hier, um zu lernen.",
    },
    {
      t: 125,
      dur: 5,
      freq: 600,
      volume: 5,
      pan: 0.9,
      mood: "strict",
      text: "Noch einmal. Weil es nötig ist.",
    },
    {
      t: 130,
      dur: 8,
      freq: 360,
      volume: 2,
      pan: 0,
      mood: "pressure",
      text: "Atme. Aber bleib aufmerksam.",
    },
    {
      t: 142,
      dur: 4,
      freq: 560,
      volume: 5,
      pan: -1,
      mood: "stare",
      text: "Ich sagte aufmerksam.",
    },
    {
      t: 146,
      dur: 4,
      freq: 520,
      volume: 5,
      pan: 1,
      mood: "strict",
      text: "Sehr gut. Jetzt verstehst du es langsam.",
    },
    {
      t: 150,
      dur: 8,
      freq: 480,
      volume: 4,
      pan: 0,
      mood: "neutral",
      text: "Das nächste Mal gehorchst du früher.",
    },
    {
      t: 158,
      dur: 5,
      freq: 600,
      volume: 5,
      pan: -1,
      mood: "stare",
      text: "Eine letzte Erinnerung.",
    },
    {
      t: 163,
      dur: 5,
      freq: 560,
      volume: 5,
      pan: 1,
      mood: "strict",
      text: "Und noch eine, damit es sitzt.",
    },
    {
      t: 168,
      dur: 7,
      freq: 420,
      volume: 3,
      pan: 0,
      mood: "pressure",
      text: "Gut. Stillhalten zahlt sich aus.",
    },
    {
      t: 175,
      dur: 5,
      freq: 320,
      volume: 1,
      pan: 0,
      mood: "neutral",
      text: "Fertig. Fürs Erste.",
    },
  ], // Array mit den aktuellen Werten
};

export const defaultCalibration = {
  220: { minGain: 0.18, maxGain: 0.24 },
  260: { minGain: 0.2, maxGain: 0.26 },
  280: { minGain: 0.2, maxGain: 0.26 },
  320: { minGain: 0.21, maxGain: 0.26 },
  360: { minGain: 0.21, maxGain: 0.29 },
  420: { minGain: 0.22, maxGain: 0.29 },
  440: { minGain: 0.22, maxGain: 0.3 },
  480: { minGain: 0.24, maxGain: 0.36 },
  520: { minGain: 0.26, maxGain: 0.35 },
  560: { minGain: 0.24, maxGain: 0.35 },
  600: { minGain: 0.24, maxGain: 0.35 },
  660: { minGain: 0.24, maxGain: 0.35 },
  880: { minGain: 0.24, maxGain: 0.35 },
};

export const videos = {
  neutral: "/src/assets/pam/pam_idle_neutral.mp4",
  soft: "/src/assets/pam/pam_listen_soft.mp4",
  strict: "/src/assets/pam/pam_listen_strict.mp4",
  stare: "/src/assets/pam/pam_judge_long_stare.mp4",
  laugh: "/src/assets/pam/pam_laughing_soft.mp4",
  pressure: "/src/assets/pam/pam_wait_silent_pressure.mp4",
};
